# Generated by Django 2.2.5 on 2019-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=40)),
                ('post_date', models.DateTimeField()),
                ('category', models.CharField(max_length=40)),
                ('text', models.TextField()),
                ('is_publish', models.BooleanField(default=True)),
            ],
        ),
    ]
