# Generated by Django 2.2.5 on 2019-09-27 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190927_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('', '-----------'), ('blog', 'ブログ'), ('tweet', 'つぶやき')], max_length=40, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='公開フラグ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=40, verbose_name='投稿者名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='投稿内容'),
        ),
    ]
